parameters:
- name: tf-app-subscription-id
  default: ''
- name: tf-app-tenant-id
  default: ''
- name: tf-app-id
  default: ''
- name: tf-app-pw
  default: ''
- name: env
  default: ''
- name: backend_config
  default: ''
- name: known_host
  default: ''
- name: ssh_public_key
  default: ''
- name: sshKeySecureFile
  default: ''

jobs:
- job: Terraform ${{ parameters.env }}
  displayName: Terraform ${{ parameters.env }}
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: $(known_host)
      sshPublicKey: $(ssh_public_key)
      sshKeySecureFile: $(sshKeySecureFile)
  - script: |
      export ARM_SUBSCRIPTION_ID="${{ parameters.tf-app-subscription-id }}"
      export ARM_TENANT_ID=${{ parameters.tf-app-tenant-id }}
      export ARM_CLIENT_ID=${{ parameters.tf-app-subscription-id }}
      export ARM_CLIENT_SECRET=${{ parameters.tf-app-pw }}
      pwd
      ls -al
      echo $ARM_SUBSCRIPTION_ID
      echo $ARM_TENANT_ID
      echo $ARM_CLIENT_ID
      echo $ARM_CLIENT_SECRET
      cd scripts
      terraform init -backend-config=${{ parameters.backend_config }}
  - script: |
      export ARM_SUBSCRIPTION_ID="${{ parameters.tf-app-subscription-id }}"
      export ARM_TENANT_ID=${{ parameters.tf-app-tenant-id }}
      export ARM_CLIENT_ID=${{ parameters.tf-app-subscription-id }}
      export ARM_CLIENT_SECRET=${{ parameters.tf-app-pw }}
      pwd
      ls -al
      echo subscription_id is $ARM_SUBSCRIPTION_ID
      echo tenant_id is $ARM_TENANT_ID
      echo client_id is $ARM_CLIENT_ID
      echo secret is $ARM_CLIENT_SECRET     
      cd scripts
      echo Starting TF Plan...
      terraform plan -var-file=../config/dev-poc/parameters.tf -var-file=../config/dev-poc/applicationinsights.auto.tfvars -var-file=../config/dev-poc/resourcegroups.auto.tfvars -var subscription_id=$(tf-app-subscription-id) -var tenant_id=$(tf-app-tenant-id)